export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  PENDING = 'PENDING',
  SOLD = 'SOLD',
  CANCELED = 'CANCELED',
  MAINTENANCE = 'MAINTENANCE',
  RENTED = 'RENTED',
}
